### ISSUE TITLE
DRY Principle (Unnecessary duplication)

### ISSUE THREAD

**Issue by geraldsanga** [ioi2908/StackOverflow-web-scraper-app#2]
Why do we need a requirement.py file if all dependencies and packages are already in requirement.txt! 
@maen08

**Comment by maen08** [comment]
Oops!!,
It has been a while since i worked on that repo.

No need for requirements.py

Thanks for your contribution, keep it up.

Let me know if wish to contribute more on this project so that i can
document it in a precise way.

**Comment by geraldsanga** [comment]
Not much of a web scrapper myself! But this comes as a source of inspiration for me to get my hands dirty in that area! I'll surely contribute in a few!
